name: big_decimal
description: Implementation close to the equivalent of BigDecimal in Java, adapted for Dart.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  decimal: ^1.3.0

dev_dependencies:

